### ISSUE TITLE
Даже комментарий с сортировкой стека удали и я притворюсь, что не видела

### ISSUE THREAD

**Issue by irina-skiba** [krilop/labs#1]
https://github.com/krilop/labs/blob/c8c658f991064f5681b8193a34502ccd1ef03185/term2/lab2/functions.c#L118

**Comment by irina-skiba** [comment]
Лучше тогда просто односвязный список использовать

**Comment by krilop** [comment]
Алгоритм поменял, комментарий удалил. Проблема уже не актуальна.
